name:   Test Python Code

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:        

jobs:
    lint: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with :
                python-version: "3.11"
                cache: "pip"  
            - name: Install poetry
              run:
                 python -m pip install poetry
            - name: Install dependencies
              run:  
               poetry install  
            - name: Run pytest
              run: pytest


        



